"""
Daily scanner runner — Sachoki Screener
Runs at 5pm ET after market close.

Steps:
1. Read today's ultra CSV (already generated by main screener)
2. Filter TIER 1 + TIER 2 picks
3. POST to /portfolio/entry
4. Next morning: POST to /portfolio/entry-price with actual opens
5. Each evening: POST daily prices + run /portfolio/daily-check

Usage:
  python daily_scanner_runner.py --action scan  --file ultra_sp500_1D_2026-05-10.csv
  python daily_scanner_runner.py --action entry --prices KRNY:8.20,BLLN:92.95,CSCO:97.10
  python daily_scanner_runner.py --action check --prices KRNY:8.22:8.35:8.15:8.28,...
"""

import argparse, requests, pandas as pd
from datetime import date

API = "http://localhost:8000/portfolio"

TIER1_CRITERIA = dict(ultra_score_min=88, change_pct_max=5.0)
TIER2_CRITERIA = dict(ultra_score_min=64, change_pct_max=10.0,
                      beta_zone_ok=['WATCH','BUILDING','SHORT_WATCH'])

def scan(file_path: str, signal_date: str):
    df = pd.read_csv(file_path)
    df = df[df['tz_sig'].notna() & df['tz_sig'].str.startswith('T')]

    entries = []

    # TIER 1
    t1 = df[
        (df['ultra_score'] >= TIER1_CRITERIA['ultra_score_min']) &
        (df['change_pct'].abs() <= TIER1_CRITERIA['change_pct_max']) &
        (df['ultra_score_cap_reason'].isna())
    ].sort_values('ultra_score', ascending=False).head(5)

    for _, r in t1.iterrows():
        entries.append(make_entry(r, 'TIER1', signal_date))

    # TIER 2
    t2 = df[
        (df['ultra_score'] >= TIER2_CRITERIA['ultra_score_min']) &
        (df['ultra_score'] < TIER1_CRITERIA['ultra_score_min']) &
        (df['change_pct'].abs() <= TIER2_CRITERIA['change_pct_max']) &
        (df['beta_zone'].isin(TIER2_CRITERIA['beta_zone_ok']))
    ].sort_values(['beta_score','ultra_score'], ascending=False).head(10)

    for _, r in t2.iterrows():
        entries.append(make_entry(r, 'TIER2', signal_date))

    print(f"TIER1: {len(t1)}, TIER2: {len(t2)}")
    resp = requests.post(f"{API}/entry", json=entries)
    print(resp.json())

def make_entry(r, tier, signal_date):
    beta_zone = str(r.get('beta_zone',''))
    hold = 20 if beta_zone == 'OPTIMAL' else 10
    return {
        "signal_date":      signal_date,
        "ticker":           str(r['ticker']),
        "exchange":         "NQ" if 'nasdaq' in str(r.get('profile_name','NQ')).lower() else "SP500",
        "ultra_score":      int(r['ultra_score']) if pd.notna(r['ultra_score']) else None,
        "ultra_band":       str(r.get('ultra_score_band_v2','')),
        "ultra_priority":   str(r.get('ultra_score_priority','')),
        "beta_score":       int(r['beta_score']) if pd.notna(r.get('beta_score')) else None,
        "beta_zone":        beta_zone,
        "tz_sig":           str(r.get('tz_sig','')),
        "turbo_score":      int(r['turbo_score']) if pd.notna(r.get('turbo_score')) else None,
        "rtb_total":        int(r['rtb_total']) if pd.notna(r.get('rtb_total')) else None,
        "rtb_phase":        str(r.get('rtb_phase','')),
        "sweet_spot":       bool(r.get('sweet_spot_active', False)),
        "tier":             tier,
        "signal_reasons":   str(r.get('ultra_score_reasons','')),
        "signal_price":     float(r['last_price']) if pd.notna(r.get('last_price')) else None,
        "signal_change_pct":float(r['change_pct']) if pd.notna(r.get('change_pct')) else None,
        "hold_days":        hold,
    }

def set_entry_prices(prices_str: str, entry_date: str):
    """prices_str: 'KRNY:8.20,BLLN:92.95,CSCO:97.10'"""
    payload = []
    for item in prices_str.split(','):
        ticker, price = item.split(':')
        payload.append({"ticker": ticker.strip(),
                        "entry_date": entry_date,
                        "open_price": float(price)})
    resp = requests.post(f"{API}/entry-price", json=payload)
    print(resp.json())

def daily_check(prices_str: str, price_date: str):
    """prices_str: 'TICKER:open:high:low:close,...'"""
    price_payload = []
    for item in prices_str.split(','):
        parts = item.split(':')
        price_payload.append({
            "ticker":     parts[0].strip(),
            "price_date": price_date,
            "open":  float(parts[1]),
            "high":  float(parts[2]),
            "low":   float(parts[3]),
            "close": float(parts[4]),
        })
    r1 = requests.post(f"{API}/daily-prices", json=price_payload)
    print("Prices:", r1.json())
    r2 = requests.post(f"{API}/daily-check")
    print("Check:", r2.json())

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--action", choices=["scan","entry","check"], required=True)
    p.add_argument("--file",   help="CSV path for scan action")
    p.add_argument("--prices", help="prices string for entry/check actions")
    p.add_argument("--date",   default=str(date.today()))
    args = p.parse_args()

    if args.action == "scan":
        scan(args.file, args.date)
    elif args.action == "entry":
        set_entry_prices(args.prices, args.date)
    elif args.action == "check":
        daily_check(args.prices, args.date)
