"""Append-only durable ledger. REGISTERED is a promise, and a promise cannot live in RAM.

`ResearchSession` kept its events in a list, which was honest for an exploratory working object
and wrong the moment a session can freeze. A registration that a process restart can forget is
not a registration; it is a note. So the ledger moves to disk with the properties that make it
worth trusting:

    append-only            no event is ever rewritten or removed
    atomic append          a reader sees the old state or the new one, never half of one
    unique event_id        (session_id, event_id) is the primary key
    chain continuity       prior_state_hash must equal the previous event's new_state_hash
    idempotent mutation    a retried request does not become a second CLAIM_CHANGE
    fail-closed recovery   a broken chain makes the session INVALID; nothing is guessed

THE TWO KINDS OF DAMAGE, WHICH ARE NOT THE SAME. A torn LAST line is an interrupted append: the
event never completed, so the correct reading is the state before it. That is not corruption,
that is the crash semantics working. A malformed or chain-breaking line in the MIDDLE is
corruption: something happened after that event which the file can no longer describe, and the
only safe answer is INVALID. Reconstructing "as much as possible" would produce a session whose
accounting is smaller than the truth, which is the exact direction that flatters a result.

WHY IDEMPOTENCY IS AN INTEGRITY CONTRACT AND NOT A CONVENIENCE. The browser posts a change, the
server appends the event, the response is lost, the browser retries. Without a key that is one
user action and two CLAIM_CHANGE events — `k` inflated by a network failure.

The key is generated by the CLIENT, once per user action, and that is not an implementation
detail. Deriving it on the server from the request payload looks tidier and is wrong: turning
the same knob to the same value twice on purpose is a revisit, and a payload-derived key would
erase the second one. Only the client knows whether this is a new intention or the same one
travelling twice.

Which leaves the opposite danger — a client that reuses a key for a different request, hiding a
real change behind an old one. So the key is stored with a hash of the request it authorised,
and the same key arriving with different arguments is a conflict, not a match. The two failure
modes are then closed in both directions: a retry cannot inflate `k`, and a stale key cannot
suppress a change.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import asdict, dataclass, field

OK, TORN_TAIL, CORRUPT = "OK", "TORN_TAIL_DISCARDED", "CORRUPT"
# A ledger that was created and is now gone. Distinct from CORRUPT, and very
# distinct from empty: an empty ledger says "nothing has been looked at", and that
# is the reading a vanished file must never be given for free.
ABSENT = "ABSENT"


class LedgerCorruptError(Exception):
    """The durable history cannot be verified. A session in this state is INVALID, not partial."""


class ChainBreakError(LedgerCorruptError):
    """An event does not continue the state it claims to continue."""


class LedgerMissingError(LedgerCorruptError):
    """The ledger file existed when this process started and does not exist now."""


class IdempotencyConflictError(Exception):
    """One key, two different requests. Answering either one would be a guess."""


@dataclass(frozen=True)
class StoredEvent:
    seq: int                     # global append order, across every session
    session_id: str
    family_id: str
    event_id: int                # per-session, monotone from 0
    event_type: str
    claim_hash: str = ""
    payload: dict = field(default_factory=dict)
    prior_state_hash: str = ""
    new_state_hash: str = ""
    state: str = ""              # the session's state AFTER this event
    code_hash: str = ""
    idempotency_key: str = ""
    request_hash: str = ""       # what this key authorised; a different one is a conflict

    def line(self) -> str:
        """One JSON object plus a checksum of it. The checksum is what detects a torn write."""
        body = json.dumps(asdict(self), sort_keys=True, separators=(",", ":"))
        return json.dumps({"e": json.loads(body),
                           "c": hashlib.sha256(body.encode()).hexdigest()[:16]},
                          sort_keys=True, separators=(",", ":")) + "\n"


def _parse(line: str) -> StoredEvent | None:
    """None means this line is not a complete, self-consistent event."""
    try:
        rec = json.loads(line)
        body = json.dumps(rec["e"], sort_keys=True, separators=(",", ":"))
        if hashlib.sha256(body.encode()).hexdigest()[:16] != rec["c"]:
            return None
        return StoredEvent(**rec["e"])
    except Exception:                                               # noqa: BLE001
        return None


class DurableLedger:
    """One file, every session. Reads are filtered; writes are appends and nothing else."""

    def __init__(self, path: str):
        self.path = path
        os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
        if not os.path.exists(path):
            with open(path, "w"):
                pass

    # ── writing ─────────────────────────────────────────────────────────────
    def append(self, session_id: str, family_id: str, event_type: str, *,
               event_id: int, prior_state_hash: str, new_state_hash: str,
               claim_hash: str = "", payload: dict | None = None, state: str = "",
               code_hash: str = "", idempotency_key: str = "",
               request_hash: str = "") -> StoredEvent:
        """Append one event. A repeated key returns the original; a reused key is a conflict."""
        events = self.read_all()

        if idempotency_key:
            for e in events:
                if e.idempotency_key != idempotency_key:
                    continue
                if e.request_hash == request_hash:
                    return e                   # the retry, answered with the original event
                raise IdempotencyConflictError(
                    f"idempotency key {idempotency_key} already authorised a different request "
                    f"({e.request_hash} vs {request_hash}). Treating this as the same action "
                    f"would hide a real change behind an old one; treating it as new would let a "
                    f"retry inflate k. Neither is answerable, so it is refused.")

        head = [e for e in events if e.session_id == session_id]
        if head:
            last = head[-1]
            if last.new_state_hash != prior_state_hash:
                raise ChainBreakError(
                    f"append to {session_id} claims to continue {prior_state_hash!r} but the "
                    f"persisted head is {last.new_state_hash!r}. Two writers, or a lost event.")
            if event_id != last.event_id + 1:
                raise ChainBreakError(
                    f"event_id {event_id} does not follow {last.event_id} in {session_id}")
        elif event_id != 0:
            raise ChainBreakError(f"first event of {session_id} has event_id {event_id}")

        ev = StoredEvent(seq=len(events), session_id=session_id, family_id=family_id,
                         event_id=event_id, event_type=event_type, claim_hash=claim_hash,
                         payload=payload or {}, prior_state_hash=prior_state_hash,
                         new_state_hash=new_state_hash, state=state, code_hash=code_hash,
                         idempotency_key=idempotency_key, request_hash=request_hash)

        # one write syscall on an O_APPEND descriptor, then fsync. A crash lands either before
        # the bytes or after them; a partial line is caught on read by its checksum.
        fd = os.open(self.path, os.O_WRONLY | os.O_APPEND | os.O_CREAT, 0o644)
        try:
            os.write(fd, ev.line().encode())
            os.fsync(fd)
        finally:
            os.close(fd)
        return ev

    # ── reading ─────────────────────────────────────────────────────────────
    def status(self) -> tuple[str, list[StoredEvent]]:
        """Classify the file before trusting it. TORN_TAIL is survivable; CORRUPT is not."""
        if not os.path.exists(self.path):
            # The constructor creates this file, so its absence here means it was removed while
            # the process was running. Reported as ABSENT rather than raised from `open()`,
            # because a bare FileNotFoundError from four frames down says nothing about what
            # was lost — and answering "zero events" would silently reset k to nothing.
            return ABSENT, []
        with open(self.path, "r") as f:
            raw = f.read()
        lines = raw.split("\n")
        if lines and lines[-1] == "":
            lines.pop()                       # the trailing newline of a complete last event

        events: list[StoredEvent] = []
        for i, line in enumerate(lines):
            ev = _parse(line)
            if ev is None:
                if i == len(lines) - 1:
                    return TORN_TAIL, events  # interrupted append: the event never happened
                return CORRUPT, []            # damage before the end: nothing here is trustworthy
            events.append(ev)

        # the chain, per session
        heads: dict = {}
        for ev in events:
            prev = heads.get(ev.session_id)
            if prev is None:
                if ev.event_id != 0:
                    return CORRUPT, []
            elif prev.new_state_hash != ev.prior_state_hash or ev.event_id != prev.event_id + 1:
                return CORRUPT, []
            heads[ev.session_id] = ev
        return OK, events

    def read_all(self) -> list[StoredEvent]:
        st, events = self.status()
        if st == ABSENT:
            raise LedgerMissingError(
                f"{self.path} existed when this process started and is gone now. Every session "
                f"it recorded is unaccounted for, and the convenient reading — 'then nothing has "
                f"been looked at' — would reset k to zero, which is the answer that always "
                f"flatters. Restore the file, or restart the process to start a new ledger "
                f"deliberately rather than by accident.")
        if st == CORRUPT:
            raise LedgerCorruptError(
                f"{self.path} does not verify. Every session it describes is INVALID. The history "
                f"is not reconstructed from the readable part, because a partial ledger under-"
                f"counts exposures and the undercount always flatters the result.")
        return events

    def read_session(self, session_id: str) -> list[StoredEvent]:
        return [e for e in self.read_all() if e.session_id == session_id]

    def sessions(self) -> list[str]:
        seen, out = set(), []
        for e in self.read_all():
            if e.session_id not in seen:
                seen.add(e.session_id)
                out.append(e.session_id)
        return out

    def families(self) -> dict:
        fam: dict = {}
        for e in self.read_all():
            fam.setdefault(e.family_id, [])
            if e.session_id not in fam[e.family_id]:
                fam[e.family_id].append(e.session_id)
        return fam


def request_hash(session_id: str, action: str, payload: dict) -> str:
    """What a key authorised. Not the key itself — the key belongs to the client."""
    blob = json.dumps({"s": session_id, "a": action, "p": payload},
                      sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(blob.encode()).hexdigest()[:24]


class ResponseLog:
    """Idempotency for HTTP mutations: one user action, one outcome, however many deliveries.

    The ledger's own key stops a duplicate EVENT. This stops a duplicate ACTION — a change that
    appends four events must replay all four or none, and the caller must get the same answer
    both times rather than a second, differently-shaped success.

    Separate from the ledger on purpose. The ledger is the research record and outlives any
    protocol; this is a transport concern, and mixing a delivery artefact into the history would
    mean the account of what was studied contains entries about what the network did.
    """

    def __init__(self, path: str):
        self.path = path
        os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
        if not os.path.exists(path):
            with open(path, "w"):
                pass

    def _rows(self) -> list:
        out = []
        with open(self.path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    out.append(json.loads(line))
                except Exception:                                   # noqa: BLE001
                    continue          # a torn tail; the action simply did not complete
        return out

    def recall(self, key: str, request_hash_: str):
        """The stored response, or None. A key reused for other arguments raises."""
        for r in self._rows():
            if r["k"] != key:
                continue
            if r["r"] != request_hash_:
                raise IdempotencyConflictError(
                    f"idempotency key {key} already answered a different request. A retry must "
                    f"be the same request; this one is not.")
            return r["v"]
        return None

    def remember(self, key: str, request_hash_: str, response) -> None:
        line = json.dumps({"k": key, "r": request_hash_, "v": response},
                          sort_keys=True, separators=(",", ":")) + "\n"
        fd = os.open(self.path, os.O_WRONLY | os.O_APPEND | os.O_CREAT, 0o644)
        try:
            os.write(fd, line.encode())
            os.fsync(fd)
        finally:
            os.close(fd)
