/**
 * colLabels.js — canonical DB-column → human label map.
 *
 * Single source of truth so every tab (Ultra, Studio, QLIB, …) shows the SAME
 * short name for a given `bars` column (e.g. sig_t9 → "T9", sig_vol_5x → "V×5").
 * These labels match the ones used in the Ultra scan filters.
 */

export const COL_TO_LABEL = {
  // Volume / VABS
  sig_va: 'VA', sig_abs: 'ABS', sig_clm: 'CLM', sig_bc: 'BC', sig_sc: 'SC',
  sig_best: 'BEST', sig_strong: 'STR', sig_best_up: 'BEST↑', sig_ns_vabs: 'NS',
  sig_nd_vabs: 'ND', sig_vbo_dn: 'VBO↓', vbo_up: 'VBO↑',
  sig_vol_5x: 'V×5', sig_vol_10x: 'V×10', sig_vol_20x: 'V×20',
  sig_fbo_up: 'FBO↑', sig_fbo_dn: 'FBO↓', sig_eb_up: 'EB↑', sig_eb_dn: 'EB↓',
  sig_3up: '3UP',
  // L / WLNBB
  sig_fri34: 'FRI34', sig_fri43: 'FRI43', sig_fri64: 'FRI64',
  sig_l555: 'L555', sig_l2l4: 'L2L4', sig_blue: 'BL',
  sig_cci: 'CCI', sig_cci0r: 'CCI0R', sig_ccib: 'CCIB',
  sig_rl: 'RL', sig_rh: 'RH', sig_pp: 'PP',
  sig_l_any: 'L★', sig_be_any: 'BE★',
  l34: 'L34', l43: 'L43', l22: 'L22',
  be_up: 'BE↑', bo_up: 'BO↑', bx_up: 'BX↑',
  // GOG
  sig_g1: 'G1', sig_g2: 'G2', sig_g4: 'G4', sig_g6: 'G6', sig_g11: 'G11',
  sig_gog_plus: 'GOG+', g1p: 'G1P', g2p: 'G2P', g3p: 'G3P',
  g1l: 'G1L', g2l: 'G2L', g1c: 'G1C', g2c: 'G2C', g3c: 'G3C',
  // F signals
  sig_f1: 'F1', sig_f2: 'F2', sig_f3: 'F3', sig_f4: 'F4', sig_f5: 'F5',
  sig_f6: 'F6', sig_f7: 'F7', sig_f8: 'F8', sig_f9: 'F9', sig_f10: 'F10',
  sig_f11: 'F11', sig_any_f: 'F★', f8: 'F8',
  // FLY
  sig_fly_abcd: 'ABCD', sig_fly_cd: 'FLY-CD', sig_fly_bd: 'FLY-BD', sig_fly_ad: 'FLY-AD',
  // WICK
  sig_wk_up: 'WK↑', sig_wk_dn: 'WK↓',
  sig_x1: 'X1', sig_x2: 'X2', sig_x1g: 'X1G', sig_x3: 'X3',
  // TZ state
  sig_tz: 'TZ', sig_t: 'T', sig_z: 'Z', sig_tz3: 'TZ3', sig_tz2: 'TZ2',
  sig_tz_flip: 'TZ→2', sig_bias_up: 'BIAS↑', sig_bias_dn: 'BIAS↓',
  tz_bull: 'TZ↑',
  // Individual T signals
  sig_t1g: 'T1G', sig_t2g: 'T2G',
  sig_t1: 'T1', sig_t2: 'T2', sig_t3: 'T3', sig_t4: 'T4',
  sig_t5: 'T5', sig_t6: 'T6', sig_t7: 'T7', sig_t8: 'T8',
  sig_t9: 'T9', sig_t10: 'T10', sig_t11: 'T11', sig_t12: 'T12',
  t_sig: 'T-state',
  // Individual Z signals
  sig_z1g: 'Z1G', sig_z2g: 'Z2G',
  sig_z1: 'Z1', sig_z2: 'Z2', sig_z3: 'Z3', sig_z4: 'Z4',
  sig_z5: 'Z5', sig_z6: 'Z6', sig_z7: 'Z7', sig_z8: 'Z8',
  sig_z9: 'Z9', sig_z10: 'Z10', sig_z11: 'Z11', sig_z12: 'Z12',
  z_sig: 'Z-state',
  // EMA cross
  sig_p2: 'P2', sig_p3: 'P3', sig_p50: 'P50', sig_p55: 'P55',
  sig_p66: 'P66', sig_p89: 'P89', sig_any_p: 'P★',
  sig_d2: 'D2', sig_d3: 'D3', sig_d50: 'D50', sig_d55: 'D55',
  sig_d66: 'D66', sig_d89: 'D89', sig_any_d: 'D★',
  // Combo / Momentum
  sig_buy: 'BUY', sig_3g: '3G', three_g: '3G', sig_conso: 'CONSO', sig_svs: 'SVS',
  sig_cd: 'CD', sig_ca: 'CA', sig_cw: 'CW', sig_seq_bcont: 'BCONT',
  sig_ns_delta: 'NS-Δ', sig_nd_delta: 'ND-Δ',
  rocket: 'ROCKET', hilo_buy: 'HILO↑', svs: 'SVS', load: 'LD', f8_dup: 'F8',
  // Delta
  sig_flp_up: 'FLIP↑', sig_org_up: 'ORG↑', sig_dd_up_red: 'ΔΔ↑', sig_d_up_red: 'Δ↑',
  sig_d_dn_green: 'Δ↓', sig_dd_dn_green: 'ΔΔ↓',
  // CISD
  sig_cisd_cplus: 'C+', sig_cisd_cplus_minus: 'C±', sig_cisd_cplus_mm: 'C±±',
  // PARA
  sig_para_prep: 'PARA-P', sig_para_start: 'PARA-S', sig_para_plus: 'PARA+', sig_para_retest: 'PARA-R',
  // Meta
  sig_not_ext: 'NOT-EXT', already_extended_flag: 'EXT⚠',
  // 260523 / Wyckoff / AD
  ad_fresh: 'AD-FR', ad_cluster: 'AD-CLU',
  wyc_spring: 'SPRING', wyc_sos: 'SOS', wyc_in_tr: 'INTR', wyc_sow: 'SOW',
  wyc_phase: 'WYC-PH',
  // Prebreak
  prebreak_prime: 'PRIME★', prebreak_ready: 'READY', prebreak_watch: 'WATCH',
  pb_lvbo: 'LVBO', pb_wvf_confirm: 'WVF', prebreak_score: 'PREBREAK',
  // Scores
  turbo_score: 'TURBO', turbo_score_n3: 'T3', turbo_score_n5: 'T5', turbo_score_n10: 'T10',
  gog_score: 'GOG', ultra_score: 'ULTRA', beta_score: 'BETA',
  aes_score: 'AES', profile_score: 'PROFILE', final_bull_score: 'BULL-SC',
  // EMA position
  price_gt_200: '↑200', price_gt_89: '↑89', price_gt_50: '↑50', price_gt_20: '↑20',
  price_lt_200: '↓200', price_lt_89: '↓89', rsi_le_35: 'RSI≤35', rsi_ge_70: 'RSI≥70',
  // Volume buckets
  vol_bucket: 'VOL-BKT', composite_vol: 'CMP-VOL', vol_sig: 'VOL-SIG', avg_vol_20d: 'AVG-V20',
  // Swing
  swing_type: 'SWING',
}

/** DB column → label, with a readable fallback for unmapped columns. Lag
 *  features generated by the QLIB lab (`<col>_lagN`) render as "<label>[-N]". */
export function colLabel(col) {
  if (!col) return col
  const lag = /^(.*)_lag(\d+)$/.exec(col)
  if (lag) return `${colLabel(lag[1])}[-${lag[2]}]`
  return COL_TO_LABEL[col] || col.replace(/^sig_/, '').toUpperCase().replace(/_/g, '-')
}
